newAcargo/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using newAcargo.Data;
using newAcargo.Interfaces;
using newAcargo.Models;
using newAcargo.Models.Cargas;
using newAcargo.Models.FrontEndUI;
using newAcargo.Services;
using static System.Net.WebRequestMethods;

namespace newAcargo.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFileProvider fileProvider;
        private readonly IOrderRepository _orderRepo;
        private readonly UserManager<ApplicationUser> _userManager;

        public CategoriesController(
            ApplicationDbContext context, 
            IFileProvider fileProvider, 
            IOrderRepository orderRepo,
             UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.fileProvider = fileProvider;
            _orderRepo = orderRepo;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = _userManager.GetUserId(User);
            var hasOrder = await _orderRepo.UserHasUncompletedOrder(user);
            if (hasOrder)
            {
                return RedirectToAction("CompleteNewOrder", "Order");
            }


            ViewBag.ImageUrl = ValueServices.ImageUrl;
            return View(await _context
                        .ShippingCategories
                        .ToListAsync()
                       );
        }

        public async Task<IActionResult> SubcategoriasList()
        {
            var contenidos = await _context
                .ContenidosDeCarga
                .Where(i => i.IsAModel == true)
                .Include(x => x.ShippingCategories)
                .Select( m => new SubcategoryListViewModel()
            {
                Id = m.Id,
                Ancho = m.Ancho,
                Alto = m.Alto,
                Profundidad = m.Profundidad,
                Peso = m.Peso,
                Categoria = m.ShippingCategories.Nombre,
                Contenido = m.Contenido
            }).ToListAsync();

            return View(contenidos);
        }
        
        public async Task<IActionResult> SubCategories(int id)
        {
            var subcategorias = await _context
                .ContenidosDeCarga
                .Where(x => x.ShippingCategoryId == id && x.IsAModel == true)
                .ToListAsync();

            ViewBag.ImageUrl = ValueServices.ImageUrl;
            ViewBag.Id = id;

            return View(subcategorias);
        }

        public async Task<IActionResult> CrearSubcategoria()
        {
            var subcateogryViewModel = new SubcategoryViewModel
            {
                Categories = await _context.ShippingCategories.Select(
                o => new SelectListItem()
                {
                    Text = o.Nombre,
                    Value = o.Id.ToString()
                }
            ).ToListAsync(),

                Unidades = await _context.Unidades.Select(
                x => new SelectListItem()
                {
                    Text = x.UnidadDeMedida,
                    Value = x.Id.ToString()
                }
            ).ToListAsync(),
                Empaques = await _context.TiposDeEmpaque.Select(
                    w => new SelectListItem()
                    {
                        Text = w.Empaque,
                        Value = w.Id.ToString()
                    }).ToListAsync()
            };
            return View(subcateogryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GuardarSubcategoria([Bind("Contenido,ImageFile,Ancho,Alto,Profundidad,Peso, SelectedUnidadId, SelectedCategoryId, SelectedEmpaque")] SubcategoryViewModel subcategory )
        {
            var archivo = "acargo_logo.png";
            if(ModelState.IsValid)
            {
                if(subcategory.ImageFile != null)
                {
                    var file = subcategory.ImageFile;
                    archivo = file.FileName;
                    var path = Path.Combine(
                           Directory.GetCurrentDirectory(), "wwwroot/images/subcategories",
                           file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    } 
                }

                var subCat = new ContenidoDeCarga
                {
                    Alto = subcategory.Alto,
                    Ancho = subcategory.Ancho,
                    Profundidad = subcategory.Profundidad,
                    Peso = subcategory.Peso,
                    Image = archivo,
                    Contenido = subcategory.Contenido,
                    IsAModel = true,

                    Unidad = await _context
                    .Unidades
                    .Where(x => x.Id == subcategory.SelectedUnidadId)
                    .FirstOrDefaultAsync(),

                    ShippingCategoryId = subcategory.SelectedCategoryId,

                    Empaque = await _context
                    .TiposDeEmpaque
                    .Where(f => f.Id == subcategory.SelectedEmpaque)
                    .FirstOrDefaultAsync()
                };

                _context.Add(subCat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SubcategoriasList));
            }

            return View(subcategory);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subcateogryViewModel = new SubcategoryViewModel
            {
                Categories = await _context
                    .ShippingCategories
                    .Select(
                o => new SelectListItem()
                {
                    Text = o.Nombre,
                    Value = o.Id.ToString()
                }
            ).ToListAsync(),

                Unidades = await _context
                    .Unidades
                    .Select(
                x => new SelectListItem()
                {
                    Text = x.UnidadDeMedida,
                    Value = x.Id.ToString()
                }
            ).ToListAsync(),

                Empaques = await _context
                .TiposDeEmpaque
                .Select( g => new SelectListItem()
                {
                    Text = g.Empaque,
                    Value = g.Id.ToString()
                }).ToListAsync()
            };

            var contenidoDeCarga = await _context
                .ContenidosDeCarga
                .Include(x => x.Unidad)
                .Include(y => y.Empaque)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (contenidoDeCarga == null)
            {
                return NotFound();
            }
            var unidad = contenidoDeCarga.Unidad;
            var empaque = contenidoDeCarga.Empaque;

            subcateogryViewModel.Id = contenidoDeCarga.Id;
            subcateogryViewModel.Alto = contenidoDeCarga.Alto;
            subcateogryViewModel.Ancho = contenidoDeCarga.Ancho;
            subcateogryViewModel.Profundidad = contenidoDeCarga.Profundidad;
            subcateogryViewModel.Peso = contenidoDeCarga.Peso;
            subcateogryViewModel.Contenido = contenidoDeCarga.Contenido;
            subcateogryViewModel.Image = contenidoDeCarga.Image;
            subcateogryViewModel.SelectedUnidadId = unidad.Id;       
            subcateogryViewModel.SelectedEmpaque = empaque.Id;
            subcateogryViewModel.SelectedCategoryId = contenidoDeCarga.ShippingCategoryId;

            return View(subcateogryViewModel);
        }


        [HttpPost]
        [Route("Categories/Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Contenido,ImageFile,Ancho,Alto,Profundidad,Peso, SelectedUnidadId, SelectedCategoryId,SelectedEmpaque")] SubcategoryViewModel subcategoryViewModel)
        {
            if (id != subcategoryViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var subcat = await _context
                    .ContenidosDeCarga
                    .SingleOrDefaultAsync(x => x.Id == id);

                subcat.Contenido = subcategoryViewModel.Contenido;
                subcat.Alto = subcategoryViewModel.Alto;
                subcat.Ancho = subcategoryViewModel.Ancho;
                subcat.Profundidad = subcategoryViewModel.Profundidad;
                subcat.Peso = subcategoryViewModel.Peso;
                subcat.IsAModel = true;
                subcat.Unidad = await _context
                    .Unidades
                    .SingleOrDefaultAsync(g => g.Id == subcategoryViewModel.SelectedUnidadId);
                subcat.Empaque = await _context
                    .TiposDeEmpaque
                    .SingleOrDefaultAsync(t => t.Id == subcategoryViewModel.SelectedEmpaque);

                subcat.ShippingCategoryId = subcategoryViewModel.SelectedCategoryId;
                subcat.ShippingCategories = await _context
                    .ShippingCategories
                    .SingleOrDefaultAsync(c => c.Id == subcategoryViewModel.SelectedCategoryId);

                try
                {
                    _context.Update(subcat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

newAcargo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]ACARGO</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-left">
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <!-- Begin page -->
    <div id="wrapper">
        <partial name="_navshippers" />
        <div class="content-page">
            <div class="content">
                <partial name="_TopHeader" />
                <div class="page-content-wrapper ">
                    <div class="container-fluid">
                        @RenderBody()
                        
                    </div>
                </div>
            </div>
            <footer class="footer">
                © 2018 ACARGO SRL - Ver <a href="#">Terminos y Condiciones</a>. Realizado por <a href="http://factoria.tech">FactoriaTECH</a>
            </footer>
            
        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/detect.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/jquery.blockUI.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/app.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    @RenderSection("Scripts", required: false)
</body>
</html>

newAcargo/Views/Shared/_Layout_Administrator.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACARGO</title>
    <!-- DataTables -->
    <link href="~/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- Responsive datatable examples -->
    <link href="~/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-left">
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <!-- Begin page -->
    <div id="wrapper">
        <partial name="_navadministrator" />
        <div class="content-page">
            <div class="content">
                <partial name="_TopHeader" />
                <div class="page-content-wrapper ">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            <footer class="footer">
                © 2018 ACARGO SRL - Ver <a href="#">Terminos y Condiciones</a>. Realizado por <a href="http://factoria.tech">FactoriaTECH</a>
            </footer>

        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/detect.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/jquery.blockUI.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/app.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Required datatable js -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <!-- Buttons examples -->
    <script src="~/plugins/datatables/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/jszip.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.html5.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.print.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.colVis.min.js" type="text/javascript"></script>
    <!-- Responsive examples -->
    <script src="~/plugins/datatables/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/responsive.bootstrap4.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

newAcargo/Views/Shared/_Layout_Carriers.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACARGO</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-left">
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <!-- Begin page -->
    <div id="wrapper">
        <partial name="_navcarriers" />
        <div class="content-page">
            <div class="content">
                <partial name="_TopHeader" />
                <div class="page-content-wrapper ">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            <footer class="footer">
                © 2018 ACARGO SRL - Ver <a href="#">Terminos y Condiciones</a>. Realizado por <a href="http://factoria.tech">FactoriaTECH</a>
            </footer>

        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/detect.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/jquery.blockUI.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/app.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    @RenderSection("Scripts", required: false)
</body>
</html>

newAcargo/Views/Shared/_Layout_Shippers_table.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACARGO</title>
    <!-- DataTables -->
    <link href="~/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- Responsive datatable examples -->
    <link href="~/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
        <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-left">
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <!-- Begin page -->
    <div id="wrapper">
        <partial name="_navshippers" />
        <div class="content-page">
            <div class="content">
                <partial name="_TopHeader" />
                <div class="page-content-wrapper ">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            <footer class="footer">
                © 2018 ACARGO SRL - Ver <a href="#">Terminos y Condiciones</a>. Realizado por <a href="http://factoria.tech">FactoriaTECH</a>
            </footer>

        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/detect.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/jquery.blockUI.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/app.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Required datatable js -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <!-- Buttons examples -->
    <script src="~/plugins/datatables/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/jszip.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.html5.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.print.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/buttons.colVis.min.js" type="text/javascript"></script>
    <!-- Responsive examples -->
    <script src="~/plugins/datatables/dataTables.responsive.min.js" type="text/javascript"></script>
    <script src="~/plugins/datatables/responsive.bootstrap4.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

newAcargo/Views/Shared/_TopHeader.cshtml
<!-- Top Bar Start -->
<div class="topbar">

    <nav class="navbar-custom">

        <ul class="list-inline float-right mb-0">
            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="~/images/users/avatar-1.jpg" alt="user" class="rounded-circle" />
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <a class="dropdown-item" href="#"><i class="mdi mdi-account-circle m-r-5 text-muted"></i> Profile</a>
                    <a class="dropdown-item" href="#"><span class="badge badge-success pull-right">5</span><i class="mdi mdi-settings m-r-5 text-muted"></i> Settings</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-lock-open-outline m-r-5 text-muted"></i> Lock screen</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-logout m-r-5 text-muted"></i> Logout</a>
                </div>
            </li>
        </ul>
        <ul class="list-inline menu-left mb-0">
            <li class="list-inline-item">
                <button type="button" class="button-menu-mobile open-left waves-effect">
                    <img src="~/images/logo-sm.png" alt="" height="24" class="logo-small" />
                </button>
            </li>
            <li class="hide-phone list-inline-item app-search">
                <h3 class="page-title"></h3>
            </li>
        </ul>
        <div class="clearfix"></div>
    </nav>
</div>

newAcargo/Views/Shared/_layout_Shippers.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACARGO</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="fixed-left">
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <!-- Begin page -->
    <div id="wrapper">
        <partial name="_navshippers" />
        <div class="content-page">
            <div class="content">
                <partial name="_TopHeader" />
                <div class="page-content-wrapper ">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            <footer class="footer">
                © 2018 ACARGO SRL - Ver <a href="#">Terminos y Condiciones</a>. Realizado por <a href="http://factoria.tech">FactoriaTECH</a>
            </footer>

        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/detect.js"></script>
    <script src="~/js/fastclick.js"></script>
    <script src="~/js/jquery.slimscroll.js"></script>
    <script src="~/js/jquery.blockUI.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/jquery.tabletojson.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    @RenderSection("Scripts", required: false)
</body>
</html>

newAcargo/Views/Shared/_layout_identity.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACARGO</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>

    <!-- Begin page -->
    <div class="accountbg"></div>
    <div class="wrapper-page">
        @RenderBody()
    </div>
<script src="~/js/jquery.min.js"></script>
            <script src="~/js/popper.min.js"></script>
            <script src="~/js/bootstrap.min.js"></script>
            <script src="~/js/modernizr.min.js"></script>
            <script src="~/js/detect.js"></script>
            <script src="~/js/fastclick.js"></script>
            <script src="~/js/jquery.slimscroll.js"></script>
            <script src="~/js/jquery.blockUI.js"></script>
            <script src="~/js/waves.js"></script>
            <script src="~/js/jquery.nicescroll.js"></script>
            <script src="~/js/jquery.scrollTo.min.js"></script>
            <script src="~/js/app.js"></script>
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
            @RenderSection("Scripts", required: false)
        </body>
</html>

newAcargo/Views/Shared/_navadministrator.cshtml
 <!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
        <i class="fas fa-times"></i>
    </button>
    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="./index.html" class="logo">
                <img src="~/images/logo.png" height="70" alt="logo" />
            </a>
        </div>
    </div>
    <div class="sidebar-inner slimscrollleft">
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Envios</li>
                <li>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-map-marker-plus"></i>
                        <span> Disponibles</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-calendar-clock"></i>
                        <span> Pendientes</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-road-variant"></i>
                        <span> En Ruta</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-truck-delivery"></i>
                        <span> Completados</span>
                    </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-files"></i><span> Sub-Categorias </span> <span class="pull-right"><i class="mdi mdi-chevron-right"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a asp-controller="Categories" asp-action="SubcategoriasList">Listado De Sub-Categorias</a></li>
                        <li><a asp-controller="Categories" asp-action="CrearSubcategoria">Crear Sub-Categoria</a></li>
                    </ul>
                </li>
                <li class="menu-title">Herramientas</li>
                <li>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-chart-histogram"></i>
                        <span> Reportes</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-account-multiple-outline"></i>
                        <span> Mis Choferes</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-truck"></i>
                        <span> Mi Flotilla</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-calculator"></i>
                        <span> Calculadora de Costos</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-wrench"></i>
                        <span> Configuracion</span>
                    </a>
                    <a href="./index.html" class="waves-effect">
                        <i class="mdi mdi-exit-to-app"></i>
                        <span> Salir</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div> <!-- end sidebarinner -->
</div>
<!-- Left Sidebar End -->