newAcargo/Models/Calculations/FormulaResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace newAcargo.Models.Calculations
{
    public class FormulaResult
    {

        public double TotalWeight { get; set; }
        public double TotalVolume { get; set; }
        public double TotalPesoVolumen { get; set; }
        public decimal TotalFf { get; set; }

        public decimal SubtotalSinFtl { get; set; }
        public string SubtotalSinFtlMoney
        {
            get { return string.Format(new System.Globalization.CultureInfo("en-US"), "{0:C}", SubtotalSinFtl); }
        }
      
        public decimal SubtotalConFtl { get; set; }
        public string SubtotalConFtlMoney
        {
            get { return string.Format(new System.Globalization.CultureInfo("en-US"), "{0:C}", SubtotalConFtl); }
        }

        public decimal Distance { get; set; }
        public decimal VolumenByDistance { get; set; }
        public FtlResult FullTruckLoad { get; set; }
      
        public decimal Subtotal { get; set; }
        public string SubTotalMoney
        {
            get { return string.Format(new System.Globalization.CultureInfo("en-US"), "{0:C}", Subtotal); }
        }




    }
}

newAcargo/Models/Calculations/PriceCalculatorViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using newAcargo.Models.Cargas;
using newAcargo.Models.Direcciones;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace newAcargo.Models.Calculations
{
    public class PriceCalculatorViewModel
    {
        public int Id { get; set; }
        public List<Carga> Cargas { get; set; }
        public double Distance { get; set; }

        public int SelectedOrigen { get; set; }
        public List<SelectListItem> Origen { get; set; }

        public int SelectedDestino { get; set; }
        public List<SelectListItem> Destino { get; set; }

        [Display(Name = "Selecciona Tipo de Empaque")]
        public int SelectedEmpaqueId { get; set; }
        public List<SelectListItem> Empaques { get; set; }



    }
}

newAcargo/Controllers/PriceCalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using newAcargo.Data;
using newAcargo.Interfaces;
using newAcargo.Models.Calculations;

namespace newAcargo.Controllers
{
    public class PriceCalculatorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPriceCalculation _price;
        private readonly IGMap _gmap;
        public PriceCalculatorController(ApplicationDbContext context, IPriceCalculation price, IGMap gmap)
        {
            _context = context;
            _price = price;
            _gmap = gmap;
        }


        // GET: Calculator
        public async Task<IActionResult> Index()
        {
            var provincias = await _context.Provincias.Select(x => new SelectListItem
            {
                Text = x.NombreProvincia,
                Value = x.Id.ToString()
            }).OrderBy(m => m.Text).ToListAsync();

            var model = new PriceCalculatorViewModel();
            model.Origen = provincias;
            model.Destino = provincias;
            model.Empaques = await _context.TiposDeEmpaque.Select(x => new SelectListItem
            {
                Text = x.Empaque,
                Value = x.Id.ToString()
            }).ToListAsync();

            return View(model);
        }


        public async Task<IActionResult> Tryouts()
        {
            var provincias = await _context.Provincias.Select(x => new SelectListItem
            {
                Text = x.NombreProvincia,
                Value = x.Id.ToString()
            }).OrderBy(m => m.Text).ToListAsync();

            var model = new PriceCalculatorViewModel();
            model.Origen = provincias;
            model.Destino = provincias;
            model.Empaques = await _context.TiposDeEmpaque.Select(x => new SelectListItem
            {
                Text = x.Empaque,
                Value = x.Id.ToString()
            }).ToListAsync();

            return View(model);
        }




        [HttpPost]
        public async Task<IActionResult> GetPrices(CargaPriceCalculatorBinding cargaPriceCalculatorBinding)
        {
            var origen = await _context
                .Provincias
                .SingleOrDefaultAsync(x => x.Id == cargaPriceCalculatorBinding.ProvinciaOrigen);
            var destino = await _context
                .Provincias
                .SingleOrDefaultAsync(x => x.Id == cargaPriceCalculatorBinding.ProvinciaDestino);

            string origenString = origen.Capital + ", " + origen.NombreProvincia;
            string destinoString = destino.Capital + ", " + destino.NombreProvincia;
            var distance = await _gmap.GetDistanceDouble(origenString, destinoString);
            var _params = await _context
                .CalculationParameterSets
                .Where(x => x.Active == true)
                .FirstOrDefaultAsync();

            var quoteValues = new QuoteValues();
            quoteValues.CargoEntrega = _params.PriceDelivery;
            quoteValues.CargoRecogida = _params.PricePickup;
            quoteValues.Distance = distance;
            quoteValues.SubTotal = await _price.GetPriceQuote(cargaPriceCalculatorBinding, distance);

            return PartialView("QuoteTotals", quoteValues);
        }

        [HttpPost]
        public async Task<IActionResult> RenderFormulaResults(CargaPriceCalculatorBinding cargaPriceCalculatorBinding)
        {
            var origen = await _context
                .Provincias
                .SingleOrDefaultAsync(x => x.Id == cargaPriceCalculatorBinding.ProvinciaOrigen);
            var destino = await _context
                .Provincias
                .SingleOrDefaultAsync(x => x.Id == cargaPriceCalculatorBinding.ProvinciaDestino);

            string origenString = origen.Capital + ", " + origen.NombreProvincia;
            string destinoString = destino.Capital + ", " + destino.NombreProvincia;
            var distance = await _gmap.GetDistanceDouble(origenString, destinoString);
            var _params = await _context
                .CalculationParameterSets
                .Where(x => x.Active == true)
                .FirstOrDefaultAsync();

            var formulaResult = await _price.GetFormulaResult(cargaPriceCalculatorBinding, distance);
            return PartialView("FormulaResults", formulaResult);
        }

        // GET: Calculator/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calculator/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calculator/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calculator/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calculator/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Calculator/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calculator/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

newAcargo/Views/PriceCalculator/FormulaResults.cshtml
@model newAcargo.Models.Calculations.FormulaResult

@{

}


<br />
<div class="card m-b-30">
    <div class="card-body">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>Distancia</td>
                    <td>@Model.Distance Km</td>
                    <td>Aqui lo que se confirma mas que todo es que la formula asuma o no la distancia minima</td>
                </tr>
                <tr>
                    <td>Factor de Frecuencia</td>
                    <td>@Model.TotalFf</td>
                    <td>Es la suma de Factor Provincia origen + factor Provincia Destino. </td>
                </tr>
                <tr>
                    <td>Volumen Total</td>
                    <td>@Model.TotalVolume CF</td>
                    <td>Es la suma de total de todo el volumen(CF). Sirve para calcular la formula FTL</td>
                </tr>
                <tr>
                    <td>Peso Total</td>
                    <td>@Model.TotalWeight Lbs</td>
                    <td>Es la suma de total de todo el Peso en Libras. Sirve para calcular la formula FTL</td>
                </tr>
                <tr>
                    <td>Peso/Volumen Total</td>
                    <td>@Model.TotalPesoVolumen Lbs/Cm3</td>
                    <td>Es la suma de total de todo el Peso/Volumen</td>
                </tr>
                <tr>
                    <td>Volumen Por Distancia</td>
                    <td>@Model.VolumenByDistance</td>
                    <td>Es la Formula (TOTAL PESO VOLUMEN) X (DISTANCIA)/(FACTOR DIVISOR)</td>
                </tr>
                <tr>
                    <td>Subtotal Sin FTL</td>
                    <td><b>@Html.DisplayFor(model => model.SubtotalSinFtlMoney)</b></td>
                    <td>Es el resultado de (VOLUMEN POR DISTANCIA) X (FACTOR DE FRECUENCIA)</td>
                </tr>
            </tbody>
        </table>
        <br />
        <h4>Full Truck Load</h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Peso Maximo</td>
                    <td>Desde</td>
                    <td>Hasta</td>
                    <td>Precio Por Km</td>
                    <td>SubTotal FTL</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.FullTruckLoad.Ftl.PesoMaximo</td>
                    <td>@Model.FullTruckLoad.Ftl.ValorDesde</td>
                    <td>@Model.FullTruckLoad.Ftl.ValorHasta</td>
                    <td>@Model.FullTruckLoad.Ftl.PrecioPorKm</td>
                    <td><b>@Html.DisplayFor(model => model.SubtotalConFtlMoney)</b></td>
                </tr>         
            </tbody>
            <tfoot>Razon de Eleccion de Tarifa: @Model.FullTruckLoad.Reason</tfoot>
        </table>
        <br />
        <h4>Subtotal Elegido: @Html.DisplayFor(model => model.SubTotalMoney)</h4>
    </div>
</div>

newAcargo/Views/PriceCalculator/Index.cshtml
@model newAcargo.Models.Calculations.PriceCalculatorViewModel


@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_layout_Shippers.cshtml";
}

<script src="~/js/jquery.min.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        
        $(sumAllCargas);

        function sumAllCargas() {
            var sum = 0;

            $(".itemPesoVolumen").each(function () {
                var value = $(this).text();
                if (!isNaN(value) && value.length != 0) {
                    sum += parseFloat(value);
                }
            });
            var num = sum.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
            $('#totalCargas').text(num);
        }



        function clearFields() {
            $('#contenido').val('');
            $('#empaque').val('');
            $('.totalcal').val('');
            $('#unidad').val('1');
            $('#apilable').val('Si');
            $('#total').val(0);

        }

        function getVolumeWeight() {
            var und = $('#unidad').val();
            var width = $('#ancho').val();
            var height = $('#alto').val();
            var lenght = $('#profundidad').val();
            var weight = $('#peso').val();
            var qty = $('#ctd').val();
            var total = 0;

            if (und == 1) {
                var vol = parseFloat(width) * parseFloat(height) * parseFloat(lenght) / 28418;
            }
            else {
                var vol = parseFloat(width) * parseFloat(height) * parseFloat(lenght) / 1728;
            }

            total = parseFloat(qty) * (vol + parseFloat(weight)) / 2;

            if (!isNaN(total)) {
                var result = total.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
                $('#total').val(result);
            }
            else {
                $('#total').val(0);
            }
        }

        function getDimensions() {
            var und = $('#unidad').val();
            var width = $('#ancho').val();
            var height = $('#alto').val();
            var lenght = $('#profundidad').val();
            var qty = $('#ctd').val();

            if (und == 1) {

                return parseFloat(width) * parseFloat(height) * parseFloat(lenght) / 28418;
            }
            
            return parseFloat(width) * parseFloat(height) * parseFloat(lenght) / 1728;
        }



        $('.totalcal').change(function () {
            getVolumeWeight();
        });

        $('#unidad').change(function () {
            getVolumeWeight();
        });

        $('#agregar').click(function () {
            var peso = $('#peso').val();
            var dimensiones = getDimensions();
            var qty = $('#ctd').val();
            var contenido = $('#contenido').val();
            var apilable = $('#apilable').val();
            var empaque = $('#empaque option:selected').text();
            var total = $('#total').val();
            var html = '<tr class="item">'
                + '<td>' + contenido + '</td>'
                + '<td>' + empaque + '</td>'
                + '<td>' + qty + '</td>'
                + '<td>' + apilable + '</td>'
                + '<td class="itemPesoVolumen">'
                + total + '</td>'
                + '<td>'
                + '<button class="btn btn-sm btn-danger delete-carga">' +
                '<i class="fa fa-trash"></i></button></td>'
                + '<td style="display: none" class="val_peso">' + peso + '</td>'
                + '<td style="display: none" class="val_dimensiones">' + dimensiones + '</td></tr>';

            if (total == 0) {
                return;
            }

            $('#listadoDeCargas tr:last').after(html);
            clearFields();
            sumAllCargas();
        });

        $(document.body).on('click', '.delete-carga', function () {
            $(this).parent().parent().remove();
            sumAllCargas();
        });


        $('#saveCargas').click(function () {
             GetPrices();
           
        });

        function sumColumns(className)
        {
            var sum = 0;
            $(className).each(function () {
                var value = $(this).text();
                if (!isNaN(value) && value.length != 0) {
                    sum += parseFloat(value);
                }
            });

            return sum.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
        }

        function GetPrices() {
            var peso = sumColumns('.val_peso');
            var dimensiones = sumColumns('.val_dimensiones');
            var pesoVolumen = sumColumns('.itemPesoVolumen');
            var origen = $('#Origen').val();
            var destino = $('#Destino').val();

            $.ajax({
                url: "@Url.Action("GetPrices", "PriceCalculator")",
                method: 'POST',
                data: {
                    "Peso": peso,
                    "Dimensiones": dimensiones,
                    "PesoVolumen": pesoVolumen,
                    "ProvinciaOrigen": origen,
                    "ProvinciaDestino": destino
                },
               success: function (data) {
                   $('#totalize_div').html(data);
               },
               error: function (data) {
                  alert("e");
               }
            });
        }



    });
</script>

    <div class="row">
        <div class="col-md-6">
            <div class="card m-b-30">
                <h4 class="card-header mt-0">Agregar Cargas</h4>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="contenido">Contenido</label>
                                <input type="text" class="form-control form-control-sm" id="contenido" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(x => Model.SelectedEmpaqueId, htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(x => Model.SelectedEmpaqueId, new SelectList(Model.Empaques, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm", @id = "empaque" })
                                @Html.ValidationMessageFor(x => x.SelectedEmpaqueId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <label>Medidas</label>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="number" class="form-control form-control-sm totalcal" id="ancho" placeholder="W" value="0" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="number" class="form-control form-control-sm totalcal" id="alto" placeholder="H" value="0" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="number" class="form-control form-control-sm totalcal" id="profundidad" placeholder="D" value="0" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <select class="form-control form-control-sm totalcal" id="unidad">
                                    <option value="1">cm</option>
                                    <option value="2">pulg</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="peso">Peso(Lbs)</label>
                                <input type="number" class="form-control  form-control-sm totalcal" id="peso" value="0" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="ctd">Cantidad</label>
                                <input type="number" class="form-control  form-control-sm totalcal" id="ctd" value="1" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="apilable">Apilable</label>
                                <select class="form-control form-control-sm" id="apilable">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="total">Total (Peso/Volumen)</label>
                                <input type="text" class="form-control form-control-sm" id="total" readonly />
                            </div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-primary waves-effect waves-light btn-sm btn-block" id="agregar">
                        <i class="fa fa-plus"></i> Agregar
                    </button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="card m-b-30">
                        <h4 class="card-header mt-0">Desde</h4>
                        <div class="card-body">
                            <div class="form-group">
                                @Html.LabelFor(x => Model.SelectedOrigen, htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(x => Model.SelectedOrigen, new SelectList(Model.Origen, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm", @id = "Origen" })
                                @Html.ValidationMessageFor(x => x.SelectedOrigen, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card m-b-30">
                        <h4 class="card-header mt-0">Hasta</h4>
                        <div class="card-body">
                            <div class="form-group">
                                @Html.LabelFor(x => Model.SelectedDestino, htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(x => Model.SelectedDestino, new SelectList(Model.Destino, "Value", "Text"), htmlAttributes: new { @class = "form-control form-control-sm", @id = "Destino" })
                                @Html.ValidationMessageFor(x => x.SelectedDestino, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card m-b-30">
                <h4 class="card-header mt-0">Listado de Cargas</h4>
                <div class="card-body">
                    <table class="table" id="listadoDeCargas">
                        <thead>
                            <tr>
                                <th>Contenido</th>
                                <th>Empaque</th>
                                <th>Unidades</th>
                                <th>Apilable</th>
                                <th>Peso/Vol</th>
                                <th>Borrar</th>
                                <th style="display:none;">Peso</th>
                                <th style="display:none;">Dimensiones</th> 
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-8" style="text-align:right">
                            <b>Total Peso/Volumen:</b>
                        </div>
                        <div class="col-md-4" id="totalCargas" style="text-align:right;font-weight:bold;"></div>
                    </div>
                </div>
            </div>
            <button class="btn btn-success waves-effect waves-light btn-lg btn-block" id="saveCargas"><i class="fa fa-calculator"></i> Cotizar</button>
            <div id="totalize_div"></div>
        </div>
    </div>

newAcargo/Views/PriceCalculator/QuoteTotals.cshtml
@model newAcargo.Models.Calculations.QuoteValues

@{
    
}


<br />
<div class="card m-b-30">
    <div class="card-body">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>Distancia</td>
                    <td>@Model.Distance Km</td>
                </tr>
                <tr>
                    <td>Cargos Recogida</td>
                    <td>@Model.CargoRecogida</td>
                </tr>
                <tr>
                    <td>Cargos Entrega</td>
                    <td>@Model.CargoEntrega</td>
                </tr>
                <tr>
                    <td><b>Subtotal</b></td>
                    <td><b>@Model.SubTotal</b></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>